config/routes.rb
Rails.application.routes.draw do
  devise_for :controllers
  resources :meetings
  devise_for :users
  root 'users#index'
  resources :users do 
    collection do
      get "mypage"
      get "calendar"
      post "calendar2"
    end
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
    if @meetings == nil
      @meetings = "shimizu"
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    

    # Never trust parameters from the scary internet, only allow the white list through.
    
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.haml
= form_for @meeting do |f|
  - if @meeting.errors.any?
    #error_explanation
      %h2= "#{pluralize(@meeting.errors.count, "error")} prohibited this meeting from being saved:"
      %ul
        - @meeting.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :start_time
    = f.datetime_select :start_time
  .actions
    = f.submit 'Save'

app/views/meetings/edit.html.haml
%h1 Editing meeting

= render 'form'

= link_to 'Show', @meeting
\|
= link_to 'Back', meetings_path

app/views/meetings/index.html.haml
%h1 Listing meetings

%table
  %thead
    %tr
      %th Name
      %th Start time
      %th
      %th
      %th

  %tbody
    - @meetings.each do |meeting|
      %tr
        %td= meeting.name
        %td= meeting.start_time
        %td= link_to 'Show', meeting
        %td= link_to 'Edit', edit_meeting_path(meeting)
        %td= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Meeting', new_meeting_path

app/views/meetings/new.html.haml
%h1 New meeting

= render 'form'

= link_to 'Back', meetings_path

app/views/meetings/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @meeting.name
%p
  %b Start time:
  = @meeting.start_time

= link_to 'Edit', edit_meeting_path(@meeting)
\|
= link_to 'Back', meetings_path