config/routes.rb
Rails.application.routes.draw do
  devise_for :controllers
  resources :meetings
  devise_for :users
  root 'users#index'
  resources :users do 
    collection do
      get "mypage"
      get "calendar"
      post "calendar2"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new

    
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    mypage_users_path
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    mypage_users_path
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery except: :calendar2
  def index
    if user_signed_in?
      redirect_to mypage_users_path
    end

    if session[:day]
      session.clear
    end  

  end

  def mypage

  end

  def calendar
    @users = User.all

     @dates = User.select('date')
     @times = User.select('time')
    @dates1 = []
    @dates2 = []
    @dates3 = []
    @users.each do |user|
      if user.time == "1"
        @dates1 << user.date
      elsif user.time == "2" 
        @dates2 << user.date
      elsif user.time == "3"
        @dates3 << user.date  
      end  
    end

  end

  def calendar2
    session[:day] = params[:day]
    session[:time] = params[:time]
    redirect_to new_user_registration_path
  end

  private

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/calendar.html.haml
カレンダーページ
%input.caleday1{type:"hidden",value: @dates1}
%input.caleday2{type:"hidden",value: @dates2}
%input.caleday3{type:"hidden",value: @dates3}
#calendar

app/views/users/index.html.haml
.index-wrap
  .container
    .index-main
      =link_to calendar_users_path do
        .index-main__left
          無料相談・コンサル受付の方
      =link_to new_user_session_path do
        .index-main__right
          会員の方

app/views/users/index2.html.haml
実験してますわ
%iframe{:frameborder => "0", :height => "600", :scrolling => "no", :src => "https://calendar.google.com/calendar/embed?src=t64.sugano.kaito%40gmail.com&ctz=Asia%2FTokyo", :style => "border: 0", :width => "800"}

app/views/users/mypage.html.haml
.mypage-wrap
  .mypage-content
    .mypage-content__top
      お申し込みありがとうございました
    .mypage-content__main
      下記の内容でお申し込みを承利ました。ご確認下さい。
      %li.mypage-content__main--li 『自分の強みでビジネス構築し集客を仕組みかする40の基本』
      (無料。リンクを記載したメールで納品)
      %li.mypage-content__main--li 強みでビジネスクラブ・オンライン無料個別説明会
      (zoomにて実施。仮予約受付メールをお送りします)

    .mypage-content__bottom
      .mypage-content__bottom--top
        注意点
      .mypage-content__bottom--main
        %li 当方からのメールを確実に受け取っていただくため、
        %li @takahashikuniyoshi.comからメールの受信トレイに届くように必要な設定をお願い致します。

    .mypage-content__calendar
      .mypage-content__calendar--top
        予定確認用のカレンダー
      .mypage-content__calendar--main

    .mypage-content__footer
      .mypage-content__footer--top
        フェイスブックで友達になりませんか？
      .mypage-content__footer--main
        .mypage-content__footer--main__left
        .mypage-content__footer--main__right
          %li.li-top フェイスブックで高橋邦欣と友達になってみませんか？
          %li.li-main ライブ配信や限定募集、コンサル企業などのお知らせも、いち早く受け取れます。
          %li.li-bottom 友達申請は下記のURLからどうぞ。
          =link_to "https://www.facebook.com/takahashikuniyoshi",class:"facebook_link" do
            https://www.facebook.com/takahashikuniyoshi
= link_to "ログアウト", destroy_user_session_path , method: :delete